{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskchampion-sync-server.postgres-secret-name" . }}
  labels:
    {{- include "taskchampion-sync-server.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.postgres.host | b64enc }}
  port: {{ .Values.postgres.port | toString | b64enc }}
  username: {{ .Values.postgres.username | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
  database: {{ .Values.postgres.database | b64enc }}
  connection: {{ include "taskchampion-sync-server.postgres-connection" . | b64enc }}
{{- end }}