{{- if and .Values.postgres.enabled (eq .Values.postgres.existingSecret "") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskchampion-sync-server.fullname" . }}
  labels:
    {{- include "taskchampion-sync-server.labels" . | nindent 4 }}
type: Opaque
data:
  connection: {{ include "taskchampion-sync-server.postgres-connection" . | b64enc }}
{{- end -}}