sqlite:
  enabled: true
  existingPV: ""
  emptyDir:
    sizeLimit: 1Gi
  persistence:
    enabled: false

postgres:
  enabled: false

clientIdSecret: "taskchampion-client-ids"

env:
  - name: RUST_LOG
    value: info
  - name: LISTEN
    value: "0.0.0.0:8080"
  - name: CREATE_CLIENTS
    value: "false"

ingress:
  enabled: true
  hosts:
    - taskchampion.example.com
