sqlite:
  enabled: true
  existingPV: ""
  emptyDir:
    sizeLimit: 1Gi
  persistence:
    enabled: false

postgres:
  enabled: false

clientIdSecret: "taskchampion-client-ids"

env:
  RUST_LOG: info
  LISTEN: "0.0.0.0:8080"
  CREATE_CLIENTS: "false"

ingress:
  enabled: true
  hosts:
    - taskchampion.example.com
