name: docs

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  mdbook-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          # if this changes, change it in .github/workflows/checks.yml as well
          mdbook-version: '0.4.48'

      - run: mdbook build docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
